#!/bin/bash
LINE=2;
LINE=$((LINE+1));sudo apt update || { echo $LINE ; exit 1; };
LINE=$((LINE+1));sudo apt -y upgrade || { echo $LINE ; exit 1; };
LINE=$((LINE+1));sudo update-grub || { echo $LINE ; exit 1; };
#LINE=$((LINE+1));sudo apt install -y golang gnome-tweaks net-tools chromium-browser virtualbox wireshark adb fastboot libreoffice python3 python3-pip nmap exiftool neofetch docker docker-compose docker.io cheese aircrack-ng clamav|| { echo $LINE ; exit 1; };
#LINE=$((LINE+1));flatpak install pinta com.microsoft.teams androidstudio intellij-idea-community signal com.visualstudio.code/ -y || { echo $LINE ; exit 1; };
LINE=$((LINE+1));cd ~ || { echo $LINE ; exit 1; };
LINE=$((LINE+1));git clone https://github.com/marguerite/linux-bing-wallpaper;
LINE=$((LINE+1));cd ~/linux-bing-wallpaper || { echo $LINE ; exit 1; };
LINE=$((LINE+1));export GO111MODULE=on && go mod download && go mod vendor && go build || { echo $LINE ; exit 1; };
LINE=$((LINE+1));sudo cp linux-bing-wallpaper /usr/bin/ || { echo $LINE ; exit 1; };
LINE=$((LINE+1));echo -e "bingmarket: \"en-US\"\nwallpaperdir: \"\"\ndesktopenvironment: \"gnome3\"\nupdateinterval: 6h\npictureoptions: \"\"\ndefaultcommand: \"/usr/bin/feh --bg-fill\"" > ~/.config/linux-bing-wallpaper/config.yaml || { echo $LINE ; exit 1; };
LINE=$((LINE+1));mkdir -p ~/.config/systemd/user || { echo $LINE ; exit 1; };
LINE=$((LINE+1));cp -r bing-wallpaper.service ~/.config/systemd/user || { echo $LINE ; exit 1; };
LINE=$((LINE+1));systemctl --user enable bing-wallpaper || { echo $LINE ; exit 1; };
LINE=$((LINE+1));systemctl --user start bing-wallpaper || { echo $LINE ; exit 1; };
LINE=$((LINE+1));cd ~ || { echo $LINE ; exit 1; };
LINE=$((LINE+1));mkdir ~/.config/autostart;
LINE=$((LINE+1));cp ~/Dotfiles/autostart/* ~/.config/autostart/ || { echo $LINE ; exit 1; };
LINE=$((LINE+1));printf '%s\n%s\n' "echo Hello Friend" "$(cat ~/.bashrc)" > ~/.bashrc || { echo $LINE ; exit 1; };
LINE=$((LINE+1));sudo apt-get update || { echo $LINE ; exit 1; };
LINE=$((LINE+1));sudo apt-get -y upgrade || { echo $LINE ; exit 1; };
LINE=$((LINE+1));sudo apt-get -y dist-upgrade || { echo $LINE ; exit 1; };
LINE=$((LINE+1));sudo apt-get -y autoremove || { echo $LINE ; exit 1; };
LINE=$((LINE+1));echo "SUCCESS";
